// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reset.sql

package database

import (
	"context"
)

const reset = `-- name: Reset :exec
DELETE FROM users
`

// Deletes all the users in the database
// Only for development/testing purposes. Do not use.
func (q *Queries) Reset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, reset)
	return err
}
